---
- name: add image into glance
  os_image:
    auth:
      auth_url: "{{ identity_api }}"
      username: "{{ username }}"
      password: "{{ password }}"
      project_name: "{{ project_name }}"
      project_domain_name: "{{ project_domain }}"
      user_domain_name: "{{ user_domain }}"
    name: cirros-4
    container_format: bare
    disk_format: qcow2
    state: present
    filename: "/home/ubuntu/Downloads/cirros-0.4.0-x86_64-disk.img"
    validate_certs: false
